### ISSUE TITLE
三星galax note20 闪退

### ISSUE THREAD

**Issue by tasha5151** [Tencent/QMUI_Android#1068]
### 运行环境 ###

- [x] 设备型号：如：`三星galax note20`
- [x] 设备系统版本：如 `Android 11`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`2.0.0-alpha12`

### 具体问题描述 ###
调试的时候，app一启动就会闪退
#### 异常日志（堆栈） ####
2021-02-28 23:54:02.653 23286-23286/com.qmuiteam.qmuidemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qmuiteam.qmuidemo, PID: 23286
    java.lang.IllegalArgumentException: Unable to query the maximum insets for IME
        at android.view.WindowInsets.getInsetsIgnoringVisibility(WindowInsets.java:373)
        at androidx.core.view.WindowInsetsCompat$Impl30.getInsetsIgnoringVisibility(WindowInsetsCompat.java:1347)
        at androidx.core.view.WindowInsetsCompat.getInsetsIgnoringVisibility(WindowInsetsCompat.java:697)
        at com.qmuiteam.qmui.arch.SwipeBackLayout$1.onApplyWindowInsets(SwipeBackLayout.java:158)
        at com.qmuiteam.qmui.util.QMUIWindowInsetHelper$8.onApplyWindowInsets(QMUIWindowInsetHelper.java:196)
        at android.view.View.dispatchApplyWindowInsets(View.java:12056)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8344)
        at androidx.fragment.app.FragmentContainerView.onApplyWindowInsets(FragmentContainerView.java:221)
        at android.view.View.dispatchApplyWindowInsets(View.java:12058)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8344)
        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:8358)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8349)
        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:8358)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8349)
        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:8358)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8349)
        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:8358)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8349)
        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:8358)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8349)
        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:8358)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:8349)
        at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:2958)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3089)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2575)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9910)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
        at android.view.Choreographer.doFrame(Choreographer.java:744)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by laurunshen** [comment]
同上
