### ISSUE TITLE
No view found for id qmui_activity_fragment_container_id for fragment

### ISSUE THREAD

**Issue by xtexChooser** [Tencent/QMUI_Android#1113]
### 运行环境 ###

- [x] 设备型号：华为MHA AL10
- [x] 设备系统版本：Android 9.0
- [x] Gradle 版本：7.0.1
- [x] QMUI Android 版本：2.0.0-alpha11

#### 问题截图 ####

部分源码：
其他Fragment都没事，就这个LoginFragment不行
[sources.tar.gz](https://github.com/Tencent/QMUI_Android/files/7022231/sources.tar.gz)

#### Layout Inspector 文件 ####

由于这是第一个Fragment，启动后直接崩溃，导出不了

#### 异常日志（堆栈） ####
```
2021-08-20 22:26:59.430 14777-14777/warmcat.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: warmcat.android, PID: 14777
    java.lang.IllegalArgumentException: No view found for id 0x7f0800e7 (warmcat.android:id/qmui_activity_fragment_container_id) for fragment LoginFragment{b9ff10d} (6a89b332-865e-4c49-bfdd-153ace3c327f) id=0x7f0800e7 LoginFragment}
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:483)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1296)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1442)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1520)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1573)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:454)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2297)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2082)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2020)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1922)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2993)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2934)
        at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:466)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:225)
        at com.qmuiteam.qmui.arch.InnerBaseActivity.onStart(InnerBaseActivity.java:98)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1419)
        at android.app.Activity.performStart(Activity.java:7479)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3454)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2021-08-20 22:26:59.442 14777-14777/warmcat.android I/Process: Sending signal. PID: 14777 SIG: 9

```

**Comment by xtexChooser** [comment]
InitFragment是启动时的fragment，直接跳转到LoginFragment（后期会判断跳转到别的Fragment）

**Comment by xtexChooser** [comment]
Solved
