### ISSUE TITLE
git'' finished with non-zero exit value 128

### ISSUE THREAD

**Issue by youarewe** [Tencent/QMUI_Android#1155]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
编译不通过
#### 问题截图 ####
Build file 'E:\workspace\android_workspace\QMUI_Android-master\QMUI_Android-master\qmuidemo\build.gradle.kts' line: 13

Process 'command 'git'' finished with non-zero exit value 128

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.process.internal.ExecException: Process 'command 'git'' finished with non-zero exit value 128
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:414)
	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:38)
	at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:205)
	at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1170)
	at Build_gradle.runCommand(build.gradle.kts:13)
	at Build_gradle.<init>(build.gradle.kts:21)
	at Program.execute(Unknown Source)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:532)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.evaluateSecondStageOf(Interpreter.kt:456)
	at Program.execute(Unknown Source)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:532)
	at org.gradle.kotlin.dsl.execution.Interpreter.eval(Interpreter.kt:205)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.evaluate(KotlinScriptEvaluator.kt:115)

#### 异常日志（堆栈） ####
dd

**Comment by youarewe** [comment]
//删掉github中获取版本的语句就好了
import com.qmuiteam.plugin.Dep
import java.io.ByteArrayOutputStream
import java.util.*

plugins {
    id("com.android.application")
    kotlin("android")
    kotlin("kapt")
}




val gitVersion =  1


android {
    signingConfigs {
        val properties = Properties()
        val propFile = project.file("release.properties")
        if (propFile.exists()) {
            properties.load(propFile.inputStream())
        }
        create("release"){
            keyAlias = properties.getProperty("RELEASE_KEY_ALIAS")
            keyPassword = properties.getProperty("RELEASE_KEY_PASSWORD")
            storeFile = file("qmuidemo.keystore")
            storePassword = properties.getProperty("RELEASE_STORE_PASSWORD")
            enableV2Signing = true
        }
    }

    compileSdk = Dep.compileSdk
    compileOptions {
        sourceCompatibility = Dep.javaVersion
        targetCompatibility = Dep.javaVersion
    }

    kotlinOptions {
        jvmTarget = Dep.kotlinJvmTarget
        freeCompilerArgs += "-Xjvm-default=all"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = Dep.Compose.version
    }

    defaultConfig {
        applicationId = "com.qmuiteam.qmuidemo"
        minSdk = Dep.minSdk
        targetSdk = Dep.targetSdk
        versionCode = gitVersion
        versionName = Dep.QMUI.qmuiVer

        ndk {
            abiFilters.add("arm64-v8a")
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            signingConfig = signingConfigs.getByName("release")
        }
    }
}

dependencies {
    implementation(Dep.AndroidX.appcompat)
    implementation(Dep.AndroidX.annotation)
    implementation(Dep.AndroidX.activity)
    implementation(Dep.MaterialDesign.material)
    implementation(Dep.ButterKnife.butterknife)
    implementation(Dep.Compose.activity)
    implementation(Dep.Compose.constraintlayout)
    kapt(Dep.ButterKnife.compiler)
    implementation(project(":lib"))
    implementation(project(":qmui"))
    implementation(project(":arch"))
    implementation(project(":type"))
    implementation(project(":compose"))
    implementation(project(":photo"))
    implementation(project(":photo-coil"))
    implementation(project(":photo-glide"))
    implementation(project(":editor"))
    implementation(Dep.Flipper.soLoader)
    implementation(Dep.Flipper.flipper)
    kapt(project(":compiler"))
    kapt(project(":arch-compiler"))
    kapt(Dep.Glide.compiler)

    implementation("com.iqiyi.xcrash:xcrash-android-lib:3.1.0")
}
