### ISSUE TITLE
快速滑动页面崩溃No virtual method formatted

### ISSUE THREAD

**Issue by victorfan336** [Tencent/QMUI_Android#1169]
### 运行环境 ###

- [x] 设备型号：`红米k60`
- [x] 设备系统版本： `Android 14`
- [x] Gradle 版本： `7.5.0`
- [x] QMUI Android 版本：`2.1.0‘

### 具体问题描述 ###
页面布局
`<?xml version="1.0" encoding="utf-8"?>
<layout>

    <com.qmuiteam.qmui.widget.QMUIWindowInsetLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/webview_root"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/white"
            android:fitsSystemWindows="true"
            android:orientation="vertical">
            <include
                android:id="@+id/toolbar_web"
                layout="@layout/toolbar_v2"/>

            <com.qmuiteam.qmui.nestedScroll.QMUIContinuousNestedScrollLayout
                android:id="@+id/coordinator_layout"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_below="@+id/toolbar_web"
                />
            <ProgressBar
                android:id="@+id/wv_progressbar"
                style="?android:attr/progressBarStyleHorizontal"
                android:layout_width="match_parent"
                android:layout_height="3dp"
                android:layout_below="@+id/toolbar_web"
                android:max="100"
                android:progress="0"
                android:progressDrawable="@drawable/progressbar"
                android:visibility="visible" />

        </RelativeLayout>
    </com.qmuiteam.qmui.widget.QMUIWindowInsetLayout>
</layout>
`
快速滑动页面，在页面还在滚动的时候手势返回退出当前页面，页面崩溃。

#### 异常日志（堆栈） ####
`java.lang.NoSuchMethodError: No virtual method formatted([Ljava/lang/Object;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /apex/com.android.art.compatible/javalib/core-oj.jar)
                                                                                                    	at android.widget.FlingAnimationStubImpl.getOptimizeOfVelocityY(FlingAnimationStubImpl.java:200)
                                                                                                    	at android.widget.OverScroller.fling(OverScroller.java:475)
                                                                                                    	at android.widget.OverScroller.fling(OverScroller.java:441)
                                                                                                    	at com.qmuiteam.qmui.nestedScroll.QMUIContinuousNestedTopAreaBehavior$ViewFlinger.fling(QMUIContinuousNestedTopAreaBehavior.java:495)
                                                                                                    	at com.qmuiteam.qmui.nestedScroll.QMUIContinuousNestedTopAreaBehavior.onTouchEvent(QMUIContinuousNestedTopAreaBehavior.java:220)
                                                                                                    	at androidx.coordinatorlayout.widget.CoordinatorLayout.onTouchEvent(CoordinatorLayout.java:563)
                                                                                                    	at android.view.View.dispatchTouchEvent(View.java:15867)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3147)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2810)
                                                                                                    	at com.qmuiteam.qmui.nestedScroll.QMUIContinuousNestedScrollLayout.dispatchTouchEvent(QMUIContinuousNestedScrollLayout.java:518)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:551)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1908)
                                                                                                    	at android.app.Activity.dispatchTouchEvent(Activity.java:4584)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
                                                                                                    	at io.sentry.android.core.internal.gestures.WindowCallbackAdapter.dispatchTouchEvent(WindowCallbackAdapter.java:39)
                                                                                                    	at io.sentry.android.core.internal.gestures.SentryWindowCallback.dispatchTouchEvent(SentryWindowCallback.java:64)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:509)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:16145)
                                                                                                    	at com.xiaomi.mirror.MiuiMirrorImpl.isHandled(MiuiMirrorImpl.java:152)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7807)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7573)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6945)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7002)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6968)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7133)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6976)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7190)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6949)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7002)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6968)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6976)
2024-01-09 17:08:30.590 30804-30804 AndroidRuntime          com.gelonghui.luyan                  E  	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6949)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10116)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10067)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10031)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10277)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:304)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:341)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:176)
                                                                                                    	at android.os.Looper.loop(Looper.java:318)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8744)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)`

麻烦大佬看看，谢谢 @hzlzh @MoLice @chanthuang @kayo5994 @1109993488

**Comment by hust-twj** [comment]
@victorfan336 请问这个问题解决了吗？遇到了同样的问题

**Comment by victorfan336** [comment]
> @victorfan336 请问这个问题解决了吗？遇到了同样的问题

不记得具体是怎么解决的了。但是，应该是App本身的问题才导致出现的这个问题。
