### ISSUE TITLE
调用QMUIDialog报错Looper.prepare()是怎么回事？大神请帮忙

### ISSUE THREAD

**Issue by dengwuqiang19899** [Tencent/QMUI_Android#312]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
public class BaseActivity extends AppCompatActivity {
    public void setSomeoneCalled(String channelID, String account){
        new QMUIDialog.MessageDialogBuilder(BaseActivity.this)
                .setMessage(channelID+"\n请求视频通话,是否接听通话?")
                .addAction("取消", new QMUIDialogAction.ActionListener() {
                    @Override
                    public void onClick(QMUIDialog dialog, int index) {
                    }
                })
                .addAction(0, "确定", QMUIDialogAction.ACTION_PROP_NEGATIVE, new QMUIDialogAction.ActionListener() {
                    @Override
                    public void onClick(QMUIDialog dialog, int index) {
                        KLog.e("当前工作状态" );
                    }
                }).show();
    }
}
#### 异常日志（堆栈） ####
EXCEPTION: Thread-46
                                                                                Process: com.gdvictor.dbconductorcenter, PID: 13987
                                                                                java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                                    at android.os.Handler.<init>(Handler.java:200)
                                                                                    at android.os.Handler.<init>(Handler.java:114)
                                                                                    at android.app.Dialog.<init>(Dialog.java:122)
                                                                                    at android.app.Dialog.<init>(Dialog.java:167)
                                                                                    at com.qmuiteam.qmui.widget.dialog.QMUIDialog.<init>(QMUIDialog.java:54)
                                                                                    at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.create(QMUIDialogBuilder.java:253)
                                                                                    at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.create(QMUIDialogBuilder.java:242)
                                                                                    at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.show(QMUIDialogBuilder.java:231)
                                                                                    at com.gdvictor.dbconductorcenter.base.BaseActivity.setSomeoneCalled(BaseActivity.java:69)
                                                                                    at com.gdvictor.dbconductorcenter.config.InitKqwSpeech.setCallRequest(InitKqwSpeech.java:58)
                                                                                    at com.gdvictor.dbconductorcenter.config.InitKqwSpeech.onSomeonecalled(InitKqwSpeech.java:39)
                                                                                    at com.gdvictor.dbconductorcenter.model.InitKqwSpeechModel.onInviteReceived(InitKqwSpeechModel.java:57)
                                                                                    at io.agora.NativeAgoraAPI$CallBack.onInviteReceived(NativeAgoraAPI.java:35)

**Comment by cgspine** [comment]
没有在主线程调用？

**Comment by dengwuqiang19899** [comment]
@cgspine    刚建立的新项目，把去年旧项目的代码原封不动的复制过来的，用法也一样。旧项目跑起来没有问题，新项目就不行，总是报这个错。
