### ISSUE TITLE
QMUITabSegment中的内容自适应，超过父容器则滚动导致Demo崩溃。

### ISSUE THREAD

**Issue by bingbing9527** [Tencent/QMUI_Android#339]
### 运行环境 ###

- [x] 设备型号：oppo r9sp
- [x] 设备系统版本： `Android 6.1`
- [x] Gradle 版本：`3.3.0`
- [x] QMUI Android 版本：`1.1.5`

### 具体问题描述 ###
Demo中点击 QMUITabSegment 中的 内容自适应，超过父容器则滚动，Demo崩溃。

**Comment by MoLice** [comment]
请贴出奔溃日志

**Comment by bingbing9527** [comment]
08-30 15:37:13.525 6474-6474/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qmuiteam.qmuidemo, PID: 6474
    java.lang.IllegalStateException: View 'topbar' with ID 2131231017 for field 'mTopBar' was of the wrong type. See cause for more info.
        at butterknife.internal.Utils.castView(Utils.java:113)
        at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:105)
        at com.qmuiteam.qmuidemo.fragment.components.QDTabSegmentScrollableModeFragment_ViewBinding.<init>(QDTabSegmentScrollableModeFragment_ViewBinding.java:24)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at butterknife.ButterKnife.createBinding(ButterKnife.java:199)
        at butterknife.ButterKnife.bind(ButterKnife.java:172)
        at com.qmuiteam.qmuidemo.fragment.components.QDTabSegmentScrollableModeFragment.onCreateView(QDTabSegmentScrollableModeFragment.java:74)
        at com.qmuiteam.qmui.arch.QMUIFragment.newSwipeBackLayout(QMUIFragment.java:213)
        at com.qmuiteam.qmui.arch.QMUIFragment.onCreateView(QMUIFragment.java:425)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:179)
        at android.app.ActivityThread.main(ActivityThread.java:5769)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
     Caused by: java.lang.ClassCastException: com.qmuiteam.qmui.widget.QMUITopBarLayout cannot be cast to com.qmuiteam.qmui.widget.QMUITopBar
        at java.lang.Class.cast(Class.java:1505)
        at butterknife.internal.Utils.castView(Utils.java:110)
        at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:105) 
        at com.qmuiteam.qmuidemo.fragment.components.QDTabSegmentScrollableModeFragment_ViewBinding.<init>(QDTabSegmentScrollableModeFragment_ViewBinding.java:24) 
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at butterknife.ButterKnife.createBinding(ButterKnife.java:199) 
        at butterknife.ButterKnife.bind(ButterKnife.java:172) 
        at com.qmuiteam.qmuidemo.fragment.components.QDTabSegmentScrollableModeFragment.onCreateView(QDTabSegmentScrollableModeFragment.java:74) 
        at com.qmuiteam.qmui.arch.QMUIFragment.newSwipeBackLayout(QMUIFragment.java:213) 
        at com.qmuiteam.qmui.arch.QMUIFragment.onCreateView(QMUIFragment.java:425) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:179) 
        at android.app.ActivityThread.main(ActivityThread.java:5769) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676) 
    
    
    --------- beginning of system

**Comment by cgspine** [comment]
这个已经修复了的，最新版本不会
