### ISSUE TITLE
QMUITipDialog在用的时候总是报错。

### ISSUE THREAD

**Issue by Zaylour** [Tencent/QMUI_Android#388]
### 运行环境 ###

- [x] 设备型号：如：`红米note 5`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `3.1..4`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
QMUITipDialog在用的时候总是报错。
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/31010597/45277382-0f850680-b4fa-11e8-8d9b-f38145327fd4.png)

#### 异常日志（堆栈） ####
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zy.gank.gankio/com.zy.gank.gankio.mvp.view.GankioMainActivity}: android.view.InflateException: Binary XML file line #6: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
        at android.app.ActivityThread.access$1200(ActivityThread.java:165)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5593)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
     Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class <unknown>
        at android.view.LayoutInflater.createView(LayoutInflater.java:652)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
        at com.android.internal.policy.impl.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:75)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:701)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:760)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:368)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:380)
        at android.app.Dialog.setContentView(Dialog.java:517)
        at com.qmuiteam.qmui.widget.dialog.QMUITipDialog$Builder.create(QMUITipDialog.java:141)
        at com.qmuiteam.qmui.widget.dialog.QMUITipDialog$Builder.create(QMUITipDialog.java:129)
        at com.zy.gank.gankio.mvp.view.TodayFragment.initdialog(TodayFragment.kt:122)
        at com.zy.gank.gankio.mvp.presenter.TodayPresenter.TadayInfo(TodayPresenter.kt:24)
        at com.zy.gank.gankio.mvp.view.TodayFragment.initView(TodayFragment.kt:42)
        at com.zy.gank.gankio.base.kotlin.BaseFragment.onViewCreated(BaseFragment.kt:61)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1439)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
        at android.app.Activity.performStart(Activity.java:6118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:165) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5593) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)

**Comment by cgspine** [comment]
theme对吗？

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/45664863-b98b1100-bb40-11e8-9f93-9181a46c1162.png)
可是第 6 行报错，唯一的可能就是 activity 或者 dialog 的 theme 没有对上， 或者使用了 Application 的 context ?

**Comment by Zaylour** [comment]
> ![image](https://user-images.githubusercontent.com/7828876/45664863-b98b1100-bb40-11e8-9f93-9181a46c1162.png)
> 可是第 6 行报错，唯一的可能就是 activity 或者 dialog 的 theme 没有对上， 或者使用了 Application 的 context ?

可能是context用的不对，我去试试，谢谢啊

**Comment by wukuiqing49** [comment]
这个错是  使用的theme 的问题吧  我继承了一个  Theme.AppCompat.Dialog   的Theme  直接就是这   默认的却没问题  所以感觉这是  个兼容性问题吧

**Comment by wcnmtx** [comment]
你得在AndroidManifest.xml 把项目的 theme 的 parent 指向 QMUI.Compat，至此，QMUI 可以正常工作。 作者说的很清楚了。
![image](https://user-images.githubusercontent.com/8731096/50062218-dfc45980-01e0-11e9-9728-acf0d0d20a61.png)

![image](https://user-images.githubusercontent.com/8731096/50062205-c91e0280-01e0-11e9-952e-31b760ab0d75.png)
