### ISSUE TITLE
Binary XML file line #6: Error inflating class <unknown>

### ISSUE THREAD

**Issue by 985211yygg** [Tencent/QMUI_Android#488]
### 运行环境 ###

- [x] 设备型号：如：`pixel xl  xiaomi mix3`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `3.3.0`
- [x] QMUI Android 版本：`1.1.7`

### 具体问题描述 ###
遇到过N多次 使用dialog类或者popup就会布局的报错

#### 问题截图 ####

======
<resources>

    
    <style name="AppTheme" parent="QMUI.Compat.NoActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimary</item>
        <item name="colorAccent">@color/colorPrimary</item>
    </style>
</resources>
==========

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxxxxxx.xxx, PID: 27323
    android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.qmuiteam.qmui.widget.popup.QMUIPopup.setContentView(QMUIPopup.java:261)
        at com.xxxxx.xxxxx.WelcomeActivity$1.onClick(WelcomeActivity.java:59)

**Comment by 985211yygg** [comment]
> QMUIPopup 默认的 layout xml 是 qmui_popup_layout.xml，里面的几个属性使用了几个 `?attr/` 来从 theme 中获取到对应的值，如 `?attr/qmui_popup_bg`。
> 
> 请确认用来初始化 QMUIPopup 的 context，是继承了 `QMUI.Compat` 或 `QMUI.Compat.NoActionBar` 的 Activity。
> 
> 可以在创建 QMUIPopup 之前调用 `QMUIResHelper.getAttrDrawable({用来创建 Popup 的 context}, R.attr.qmui_popup_bg)` ，返回值应该非 null。

谢谢已经解决了问题，错  传了application的context
