### ISSUE TITLE
无效果

### ISSUE THREAD

**Issue by wangzhouxin** [Tencent/QMUI_Android#515]
当 parent="QMUI"，程序闪退
当 parent="QMUI.compat"时，无变化
当 parent="QMUI.Compat.NoActionBar"，颜色无变化，状态栏消失

**Comment by cgspine** [comment]
无变化时有使用 QMUI 提供的组件？ 闪退的贴一下 log 信息？

**Comment by wangzhouxin** [comment]
没有使用组件，仅引入库和配置主题
2019-02-21 19:13:31.048 6431-6431/com.example.hello E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.hello, PID: 6431
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.hello/com.example.hello.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.support.v7.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:555)
        at android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.example.hello.MainActivity.onCreate(MainActivity.java:14)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by cgspine** [comment]
1. 你在没有使用组件的时候，无效果肯定是正常的， 沉浸式那些也需要配合 QMUIStatusBarHelper 的
2. 你用了`AppCompatActivity`，所以必须用 `QMUI.compat`

**Comment by liupeng826** [comment]
不可能所有组件都使用QMUI，如果只用一部分，怎么动态改变主题呢？ @cgspine

**Comment by cgspine** [comment]
一般是把自己的主题的父类指向 QMUI 的主题， 如果父类主题无法更改，则只能将 QMUI 主题下的 全部 item 复制到自己的主题下。
