### ISSUE TITLE
MIUI设置全屏横屏显示，直接崩溃！

### ISSUE THREAD

**Issue by Viperwu** [Tencent/QMUI_Android#525]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by Theoneee** [comment]
错误日志呢。

**Comment by Viperwu** [comment]
public class CenteringActivity extends QMUIFragmentActivity {

    @Override
    protected int getContextViewId() {
        return R.id.imoapp;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (savedInstanceState == null) {
            BaseFragment fragment = getFirstFragment();
            getSupportFragmentManager()
                    .beginTransaction()
                    .add(getContextViewId(), fragment, fragment.getClass().getSimpleName())
                    .addToBackStack(fragment.getClass().getSimpleName())
                    .commit();
        }
    }

    @Override
    protected void onResume() {
        QMUIDisplayHelper.setFullScreen(this);
        if (getRequestedOrientation() != ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE) {
            setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
        }
        super.onResume();
    }


上面是代码

java.lang.RuntimeException: Unable to resume activity {com.imo.wu/com.imo.wu.zx.activity.CenteringActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3691)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3731)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2937)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:173)
	at android.app.ActivityThread.main(ActivityThread.java:6698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
Caused by: java.lang.IllegalStateException: Only fullscreen activities can request orientation
	at android.os.Parcel.readException(Parcel.java:1959)
	at android.os.Parcel.readException(Parcel.java:1897)
	at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5760)
	at android.app.Activity.setRequestedOrientation(Activity.java:5793)
	at com.imo.qmui.arch.InnerBaseActivity.setRequestedOrientation(InnerBaseActivity.java:44)
	at com.imo.qmui.arch.QMUIFragmentActivity.setRequestedOrientation(QMUIFragmentActivity.java:36)
	at com.imo.wu.zx.activity.CenteringActivity.onResume(CenteringActivity.java:41)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
	at android.app.Activity.performResume(Activity.java:7144)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3666)
	... 10 more

**Comment by Viperwu** [comment]
EMUI下正常全屏横屏显示

**Comment by Theoneee** [comment]
https://blog.csdn.net/qq_35372527/article/details/81774761
