### ISSUE TITLE
QMUIFloatLayout addView异常

### ISSUE THREAD

**Issue by yinshuai0324** [Tencent/QMUI_Android#545]
### 运行环境 ###

- [x] 设备型号：如：`android平板`
- [x] 设备系统版本：如 `Android 7.1`
- [x] Gradle 版本：如 `4.1`
- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###
往QMUIFloatLayout动态添加View 以及直接在布局文件里面添加View运行后都会报ArrayIndexOutOfBoundsException
#### 异常日志（堆栈） ####
FATAL EXCEPTION: main
                                                                Process: com.pos.single, PID: 26997
                                                                java.lang.ArrayIndexOutOfBoundsException: length=10; index=10
                                                                    at com.qmuiteam.qmui.widget.QMUIFloatLayout.onMeasure(QMUIFloatLayout.java:169)
                                                                    at android.view.View.measure(View.java:19871)
                                                                    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1632)
                                                                    at android.view.View.measure(View.java:19871)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                    at android.view.View.measure(View.java:19871)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                    at android.view.View.measure(View.java:19871)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                    at android.view.View.measure(View.java:19871)
                                                                    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1098)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:642)
                                                                    at android.view.View.measure(View.java:19871)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                    at android.view.View.measure(View.java:19871)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1117)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:642)
                                                                    at android.view.View.measure(View.java:19871)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                    at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
                                                                    at android.view.View.measure(View.java:19871)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                    at android.view.View.measure(View.java:19871)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                    at android.view.View.measure(View.java:19871)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                    at android.view.View.measure(View.java:19871)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                    at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
                                                                    at android.view.View.measure(View.java:19871)
                                                                    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
                                                                    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:621)
03-21 18:06:49.142 26997-26997/com.pos.single E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by chanthuang** [comment]
请尽量详细地提供以下信息：
- 该 QMUIFloatLayout 是在什么宽高限制下布局的？
- 该 QMUIFloatLayout 的使用方法（maxNumber、maxLines、horizontalSpacing 等属性）
- 该 QMUIFloatLayout 的子 View 的情况（数量，各个子 View 的宽高信息）

最好能提供一份导致该异常的布局 xml 或动态添加子 View 的代码。谢谢
