### ISSUE TITLE
使用 QMUIGroupListView ，程序FC，报错android.view.InflateException

### ISSUE THREAD

**Issue by MicroH** [Tencent/QMUI_Android#578]
### 运行环境 ###

- [ ] 设备型号：如：
- [x] 设备系统版本：如 `Android 8.1.0`
- [x] Gradle 版本：如 `4.10.1`
- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###
使用 QMUIGroupListView 时，打开所在页面，程序直接崩溃。

#### 问题截图 ####
无
#### Layout Inspector 文件([如何获取]
无法获取

#### 异常日志（堆栈） ####
`2019-04-24 16:30:36.631 20524-20524/com.tcl.locationkids E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tcl.locationkids, PID: 20524
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tcl.locationkids/com.tcl.locationkids.views.Settings_qmui}: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class android.widget.TextView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2865)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1663)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6606)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
     Caused by: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class android.widget.TextView
     Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class android.widget.TextView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.qmuiteam.qmui.widget.grouplist.QMUIGroupListSectionHeaderFooterView.init(QMUIGroupListSectionHeaderFooterView.java:72)
        at com.qmuiteam.qmui.widget.grouplist.QMUIGroupListSectionHeaderFooterView.<init>(QMUIGroupListSectionHeaderFooterView.java:52)
        at com.qmuiteam.qmui.widget.grouplist.QMUIGroupListSectionHeaderFooterView.<init>(QMUIGroupListSectionHeaderFooterView.java:42)
        ### at com.qmuiteam.qmui.widget.grouplist.QMUIGroupListSectionHeaderFooterView.<init>(QMUIGroupListSectionHeaderFooterView.java:56)
        at com.qmuiteam.qmui.widget.grouplist.QMUIGroupListView$Section.createSectionHeader(QMUIGroupListView.java:417)
        at com.qmuiteam.qmui.widget.grouplist.QMUIGroupListView$Section.setTitle(QMUIGroupListView.java:287)
        at com.tcl.locationkids.views.Settings_qmui.initGroupListView(Settings_qmui.java:106)
        at com.tcl.locationkids.views.Settings_qmui.onCreate(Settings_qmui.java:39)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Activity.performCreate(Activity.java:7014)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1221)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2818)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1663)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6606)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f0401ce a=-1}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:538)
        at android.widget.TextView.<init>(TextView.java:1214)
2019-04-24 16:30:36.632 20524-20524/com.tcl.locationkids E/AndroidRuntime:     at android.widget.TextView.<init>(TextView.java:820)
        at android.widget.TextView.<init>(TextView.java:816)
        	... 31 more`

**Comment by MicroH** [comment]
使用 QMUIGroupListView 时，直接打开所在页面，程序直接崩溃。

**Comment by cgspine** [comment]
Settings_qmui 是怎样的，传的 context 是否正确， QMUIDemo能否正常工作？

**Comment by MicroH** [comment]
昨天应该是传的 context 有问题。后来代码被我删掉了。今天早上重新导入代码试了下，发现是可以的。

谢谢回答！
