### ISSUE TITLE
QMUIPagerAdapter count<=3时Crash

### ISSUE THREAD

**Issue by whataa** [Tencent/QMUI_Android#625]
使用QMUIViewPager和QMUIPagerAdapter来实现loop时，如果QMUIPagerAdapter.getCount返回的值小于等于3，在往后滑动几页后再往前回滑，就会crash：
```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:3880)
        at android.view.ViewGroup.addView(ViewGroup.java:3733)
        at android.support.v4.view.ViewPager.addView(ViewPager.java:1485)
        at com.qmuiteam.qmui.widget.QMUIViewPager.addView(QMUIViewPager.java:89)
        at android.view.ViewGroup.addView(ViewGroup.java:3678)
        at android.view.ViewGroup.addView(ViewGroup.java:3654)
        at com.qmuiteam.qmuidemo.fragment.components.viewpager.QDLoopViewPagerFragment$2.populate(QDLoopViewPagerFragment.java:117)
        at com.qmuiteam.qmui.widget.QMUIPagerAdapter.instantiateItem(QMUIPagerAdapter.java:54)
        at com.qmuiteam.qmui.widget.QMUIViewPager$WrapperPagerAdapter.instantiateItem(QMUIViewPager.java:172)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1010)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1224)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
        at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:549)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

直接修改demo中对应代码的数量可复现

**Comment by cgspine** [comment]
因为 Loop 的原因吧，如果小于三个，是没办法循环的，我加下保护

**Comment by LuoboDcom** [comment]
> 因为 Loop 的原因吧，如果小于三个，是没办法循环的，我加下保护

2个的时候可以循环吧

**Comment by cgspine** [comment]
目前针对 ViewPager 的这种实现，就会会出现上述crash，所以我直接禁用掉了。

**Comment by WinnieZy** [comment]
请问下这里对count<=3时的crash有进一步的修改方案吗？

**Comment by cgspine** [comment]
我加了保护的，如果你真想两个也实现循环，我觉得你最好用 ViewPager2

**Comment by WinnieZy** [comment]
看代码是只加了count<3的保护，但count=3的情况也会crash

**Comment by cgspine** [comment]
确实是的，=3往回滑的时候会crash，打日志看，它总是先处理左边View的添加和移除，再处理右边的添加和移除。我暂时先保护下。不过这样的方案就不怎么合理了。2.0后我准备之后废弃掉它，采用ViewPager2 重新实现

**Comment by WinnieZy** [comment]
嗯嗯是的，三个的Loop是很常见的，还是需要用其它方案来实现
