### ISSUE TITLE
整体使用的QMUIFragment风格,点击返回按钮崩溃，类型转换异常

### ISSUE THREAD

**Issue by guohuan1990** [Tencent/QMUI_Android#626]
### 运行环境 ###

- [x] 设备型号：如：`华为  P9`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `3.4.1`
- [x] QMUI Android 版本：`com.qmuiteam:qmui:1.2.0

### 具体问题描述 ###
整个应用使用的fragment，很多页面点击返回按钮时就会崩溃
#### 问题截图 #### 好几种机型有同样的问题
![image](https://user-images.githubusercontent.com/25808718/59735273-7bfe1480-9287-11e9-97d8-714e2d9a68c6.png)

#### 异常日志（堆栈） ####

java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:779)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:22149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:22149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:22149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.qmuiteam.qmui.layout.QMUIFrameLayout.onMeasure(QMUIFrameLayout.java:59)
	at android.view.View.measure(View.java:22149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.qmuiteam.qmui.layout.QMUIFrameLayout.onMeasure(QMUIFrameLayout.java:59)
	at android.view.View.measure(View.java:22149)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1632)
	at com.qmuiteam.qmui.widget.QMUIViewPager.onMeasure(QMUIViewPager.java:105)
	at android.view.View.measure(View.java:22149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.qmuiteam.qmui.layout.QMUIFrameLayout.onMeasure(QMUIFrameLayout.java:59)
	at android.view.View.measure(View.java:22149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.qmuiteam.qmui.layout.QMUIFrameLayout.onMeasure(QMUIFrameLayout.java:59)
	at android.view.View.measure(View.java:22149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.qmuiteam.qmui.layout.QMUIFrameLayout.onMeasure(QMUIFrameLayout.java:59)
	at android.view.View.measure(View.java:22149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
	at android.view.View.measure(View.java:22149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:22149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:22149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:22149)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:761)
	at android.view.View.measure(View.java:22149)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2438)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1520)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1777)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1408)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6854)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6758)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by cgspine** [comment]
这 crash 原因已经说得很明显了，是你用错了 LayoutParams，不是 QMUI 的问题。
