### ISSUE TITLE
使用QMUIDialog弹全局弹框时crash

### ISSUE THREAD

**Issue by WinnieZy** [Tencent/QMUI_Android#631]
### 运行环境 ###

- [x] 设备型号：如：`小米4`
- [x] 设备系统版本：如 `Android 6.0.1`
- [x] Gradle 版本：如 `3.3.2`
- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###

使用QMUIDialog弹全局弹框时crash，加了WindowManager.LayoutParams.TYPE_SYSTEM_ALERT来设置全局弹框，不加则不会crash。

具体调用代码如下：
QMUIDialog.MessageDialogBuilder dialogBuilder = new QMUIDialog.MessageDialogBuilder(mContext)
                .setTitle(mTitle)
                .setMessage(mContent)
                .addAction("确认",new QMUIDialogAction.ActionListener() {
                    @Override
                    public void onClick(QMUIDialog dialog, int index) {
                        dialog.dismiss();
                    }
                }).addAction("取消", new QMUIDialogAction.ActionListener() {
                    @Override
                    public void onClick(QMUIDialog dialog, int index) {
                        dialog.dismiss();
                    }
                });
        QMUIDialog dialog = dialogBuilder.create();
        if (dialog.getWindow() != null) {
            dialog.getWindow().setType(WindowManager.LayoutParams.TYPE_SYSTEM_ALERT);
        }
        dialog.show();

#### 异常日志（堆栈） ####
06-26 18:11:50.895 26986-26986/com.zy.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zy.demo, PID: 26986
    android.view.InflateException: Binary XML file line #33: Binary XML file line #33: Error inflating class com.qmuiteam.qmui.widget.dialog.QMUIDialogView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.create(QMUIDialogBuilder.java:319)
        at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.create(QMUIDialogBuilder.java:305)
        at com.zy.demo.push.PushDialogManager.showUpgradeDialog(PushDialogManager.java:136)
        at com.zy.push.PushDialogManager.access$000(PushDialogManager.java:26)
        at com.zy.push.PushDialogManager$1.handleMessage(PushDialogManager.java:42)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
     Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class com.qmuiteam.qmui.widget.dialog.QMUIDialogView
        at android.view.LayoutInflater.createView(LayoutInflater.java:649)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)?
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)?
        at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.create(QMUIDialogBuilder.java:319)?
        at com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.create(QMUIDialogBuilder.java:305)?
        at com.zy.demo.push.PushDialogManager.showUpgradeDialog(PushDialogManager.java:136)?
        at com.zy.demo.push.PushDialogManager.access$000(PushDialogManager.java:26)?
        at com.zy.demo.push.PushDialogManager$1.handleMessage(PushDialogManager.java:42)?
        at android.os.Handler.dispatchMessage(Handler.java:102)?
        at android.os.Looper.loop(Looper.java:157)?
        at android.app.ActivityThread.main(ActivityThread.java:5684)?
        at java.lang.reflect.Method.invoke(Native Method)?
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)?
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)?

**Comment by cgspine** [comment]
`mContext` 是 `Activity` 吗？

**Comment by WinnieZy** [comment]
application context

**Comment by cgspine** [comment]
Dialog 是不能用 Application Context 的，可以看这篇文章： https://www.jianshu.com/p/628ac6b68c15 。我没试过 TYPE_SYSTEM_ALERT，但可能存在兼容性问题，并不安全。

**Comment by Tianyijian** [comment]
@cgspine 所以遇到需要在activity中弹出dialog这种情况该怎么解决

**Comment by cgspine** [comment]
通过 eventBus等手段通知到 activity 上去弹出。
