### ISSUE TITLE
无法运行master分支demo

### ISSUE THREAD

**Issue by tianshaokai** [Tencent/QMUI_Android#720]
### 运行环境 ###

- [x] 设备型号：如：`OPPO A79`
- [x] 设备系统版本：如 `Android 7.1.1`

### 具体问题描述 ###

无法启动master分支demo

#### 异常日志（堆栈） ####

2019-10-07 10:38:04.037 1339-12842/? D/AES: onEndOfErrorDumpThread: data_app_crash Process: com.qmuiteam.qmuidemo
    Time: 5593803329_1570415883581
    Flags: 0x3888be46
    Package: com.qmuiteam.qmuidemo v479 (1.4.0)
    PID: 12806
    Foreground: Yes
    Build: OPPO/A79/A79:7.1.1/N6F26Q/1565073096:user/release-keys
    
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qmuiteam.qmuidemo/com.qmuiteam.qmuidemo.QDMainActivity}: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2973)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3097)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:6910)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class <unknown>
     Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class <unknown>
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at com.qmuiteam.qmui.skin.QMUISkinLayoutInflaterFactory.onCreateView(QMUISkinLayoutInflaterFactory.java:50)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2010)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2721)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2828)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2134)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:99)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:59)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:55)
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:58)
        at com.qmuiteam.qmuidemo.QDMainActivity.onCreate(QDMainActivity.java:67)
        at android.app.Activity.performCreate(Activity.java:6987)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2921)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3097)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:6910)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.ViewConfiguration.getScaledTouchSlop()' on a null object reference
        at android.view.View.<init>(View.java:4112)
        at android.view.ViewStub.<init>(ViewStub.java:107)
    	at android.view.ViewStub.<init>(ViewStu
2019-10-07 10:38:04.038 1339-12842/? W/AES: Exception Log handling...

**Comment by cgspine** [comment]
我这里不会，ViewConfiguration.getScaledTouchSlop() 出现 NPE 有点神奇，看源代码是不会为 null 的？
![image](https://user-images.githubusercontent.com/7828876/66478841-db4d9200-eacd-11e9-92a1-9f0500279055.png)
你那里去掉这一行，还会出现吗？

**Comment by tianshaokai** [comment]
我试试啊

**Comment by tianshaokai** [comment]
@cgspine  不再崩溃了，大佬可否加你个微信啊，交流一下安卓学习

**Comment by tianshaokai** [comment]
oppo 系统 ColorOS v5.2.1 ，android 7.1.1

**Comment by cgspine** [comment]
那可能是 QMUISkinLayoutInflaterFactory 的兼容性问题了，我再看看。 我的微信号：cgine_song

**Comment by tianshaokai** [comment]
我刚才试了 OPPO K1 PBCM30  ColorOS 5.2 Android 8.1.0 也是一样的问题

**Comment by felixcc** [comment]
![image](https://user-images.githubusercontent.com/459409/67163403-058e3200-f3a1-11e9-909d-75899ea338ec.png)
![image](https://user-images.githubusercontent.com/459409/67163405-0aeb7c80-f3a1-11e9-91df-a4ce17936bbd.png)
哥们，我这个是什么情况？？

**Comment by felixcc** [comment]
![image](https://user-images.githubusercontent.com/459409/67163425-47b77380-f3a1-11e9-9fd0-9ce21aae169a.png)
![image](https://user-images.githubusercontent.com/459409/67163426-49813700-f3a1-11e9-961e-614589afcb85.png)
大兄弟，我这个是什么情况？

**Comment by cgspine** [comment]
如果是看demo代码，请切换到1.x分支。 master 代码需要先在本地发布skin-maker-plugin:
` ./gradlew :skin-maker-plugin:clean :skin-maker-plugin:build skin-maker-plugin:publishToMavenLocal`
