### ISSUE TITLE
             2.0.0-alpha01           demo闪退

### ISSUE THREAD

**Issue by hjywyj** [Tencent/QMUI_Android#762]
### 运行环境 ###

- [x] 设备型号：如：`红米Note4X`
- [x] 设备系统版本：如 `Android 6.0`
- [x] Gradle 版本：如 `5.6.1`
- [x] QMUI Android 版本：`2.0.0-alpha01`

### 具体问题描述 ###
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qmuiteam.qmuidemo/com.qmuiteam.qmuidemo.QDMainActivity}: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class android.view.ViewStub
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2604)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2670)
        at android.app.ActivityThread.access$1100(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5845)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
     Caused by: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class android.view.ViewStub
        at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3980)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4052)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2002)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:99)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:59)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:55)
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:60)
        at android.app.Activity.performCreate(Activity.java:6340)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2670) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5845) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768) 
     Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class android.view.ViewStub
        at android.view.LayoutInflater.createView(LayoutInflater.java:649)
        at com.qmuiteam.qmui.skin.QMUISkinLayoutInflaterFactory.onCreateView(QMUISkinLayoutInflaterFactory.java:63)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3980) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4052) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2002) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:99) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:59) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:55) 
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:60) 
        at android.app.Activity.performCreate(Activity.java:6340) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2670) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5845) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:623)
        at com.qmuiteam.qmui.skin.QMUISkinLayoutInflaterFactory.onCreateView(QMUISkinLayoutInflaterFactory.java:63) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3980) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4052) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2002) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:99) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:59) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:55) 
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:60) 
        at android.app.Activity.performCreate(Activity.java:6340) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2670) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5845) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
        at miui.util.AttributeResolver.isUsingMiuiTheme(SourceFile:180)
        at miui.os.Environment.isUsingMiui(SourceFile:108)
        at android.view.ViewConfigurationInjector.get(ViewConfigurationInjector.java:18)
        at android.view.ViewConfiguration.get(ViewConfiguration.java:369)
        at android.view.View.<init>(View.java:3837)
        at android.view.ViewStub.<init>(ViewStub.java:107)
        at android.view.ViewStub.<init>(ViewStub.java:103)
        at android.view.ViewStub.<init>(ViewStub.java:99)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:623) 
        at com.qmuiteam.qmui.skin.QMUISkinLayoutInflaterFactory.onCreateView(QMUISkinLayoutInflaterFactory.java:63) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3980) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4052) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2002) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:99) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:59) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:55) 
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:60) 
        at android.app.Activity.performCreate(Activity.java:6340) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2670) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5845) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)

**Comment by hjywyj** [comment]
demo可以用了，但implementation的还是报错

**Comment by cgspine** [comment]
2.0.0-alpha02 版本修复了crash， implementation 报错是指？
