### ISSUE TITLE
直接崩溃了  

### ISSUE THREAD

**Issue by MengYaoSai** [Tencent/QMUI_Android#765]
### 运行环境   AS3.5.2 ###

- [x] 设备型号：VIVO Y55
- [x] 设备系统版本：Android 6.0`

#### 问题截图 ####
![图片](https://user-images.githubusercontent.com/35183149/69926599-03ff7000-14f0-11ea-95eb-1a67ea7b078d.png)

#### 异常日志（堆栈） ####
12-02 10:38:28.612 10507-10507/com.qmuiteam.qmuidemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qmuiteam.qmuidemo, PID: 10507
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qmuiteam.qmuidemo/com.qmuiteam.qmuidemo.QDMainActivity}: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class android.view.ViewStub
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2514)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574)
        at android.app.ActivityThread.access$1000(ActivityThread.java:166)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
     Caused by: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class android.view.ViewStub
        at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4162)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4234)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2054)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:717)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:543)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:166)
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:62)
        at android.app.Activity.performCreate(Activity.java:6309)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:166) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5563) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 
     Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class android.view.ViewStub
        at android.view.LayoutInflater.createView(LayoutInflater.java:654)
        at com.qmuiteam.qmui.skin.QMUISkinLayoutInflaterFactory.onCreateView(QMUISkinLayoutInflaterFactory.java:63)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:880)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:843)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:521)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4162) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4234) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2054) 
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:717) 
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:543) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:166) 
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:62) 
        at android.app.Activity.performCreate(Activity.java:6309) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:166) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5563) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:628)
        at com.qmuiteam.qmui.skin.QMUISkinLayoutInflaterFactory.onCreateView(QMUISkinLayoutInflaterFactory.java:63) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:880) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:843) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:521) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4162) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4234) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2054) 
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:717) 
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:543) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:166) 
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:62) 
        at android.app.Activity.performCreate(Activity.java:6309) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:166) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5563) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.view.ViewConfiguration.get(ViewConfiguration.java:364)
        at android.view.View.<init>(View.java:3802)
        at android.view.ViewStub.<init>(ViewStub.java:107)
        at android.view.ViewStub.<init>(ViewStub.java:103)
        at android.view.ViewStub.<init>(ViewStub.java:99)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:628) 
        at com.qmuiteam.qmui.skin.QMUISkinLayoutInflaterFactory.onCreateView(QMUISkinLayoutInflaterFactory.java:63) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:880) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:843) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:521) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4162) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4234) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2054) 
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:717) 
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:543) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:166) 
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:62) 
        at android.app.Activity.performCreate(Activity.java:6309) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:166) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5563) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by cgspine** [comment]
2.0.0-alpha02 版本修复了
