### ISSUE TITLE
2.0 demo闪退

### ISSUE THREAD

**Issue by DaveBoy** [Tencent/QMUI_Android#766]
### 运行环境 ###

- [x] 设备型号：`华为荣耀8青春版 pra al00(刷过机)`
- [x] 设备系统版本： `Android 7.0`
- [x] QMUI Android 版本：`2`

### 具体问题描述 ###
点击闪退，无法进入首页，不知道是不是因为我刷过机的原因

#### 异常日志（堆栈） ####
```
2019-12-02 11:09:31.224 21353-21353/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qmuiteam.qmuidemo, PID: 21353
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qmuiteam.qmuidemo/com.qmuiteam.qmuidemo.QDMainActivity}: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class <unknown>
     Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class <unknown>
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:656)
        at com.qmuiteam.qmui.skin.QMUISkinLayoutInflaterFactory.onCreateView(QMUISkinLayoutInflaterFactory.java:63)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1881)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2725)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2814)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2110)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:99)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:59)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:55)
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:60)
        at android.app.Activity.performCreate(Activity.java:6910)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.view.ViewConfiguration.get(ViewConfiguration.java:365)
        at android.view.View.<init>(View.java:4019)
        at android.view.ViewStub.<init>(ViewStub.java:107)
        at android.view.ViewStub.<init>(ViewStub.java:103)
        at android.view.ViewStub.<init>(ViewStub.java:99)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:656) 
        at com.qmuiteam.qmui.skin.QMUISkinLayoutInflaterFactory.onCreateView(QMUISkinLayoutInflaterFactory.java:63) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:869) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1881) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2725) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2814) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2110) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:99) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:59) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:55) 
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:60) 
        at android.app.Activity.performCreate(Activity.java:6910) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
2019-12-02 11:09:31.231 1317-8304/? E/ReportTools: This is not beta user build
```

**Comment by lydlovezjr** [comment]
12-02 14:31:56.559 3104-3118/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-02 14:31:56.789 5052-5052/com.qmuiteam.qmuidemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qmuiteam.qmuidemo, PID: 5052
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qmuiteam.qmuidemo/com.qmuiteam.qmuidemo.QDMainActivity}: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class android.view.ViewStub
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2514)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574)
        at android.app.ActivityThread.access$1000(ActivityThread.java:166)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
     Caused by: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class android.view.ViewStub
        at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4162)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4234)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2054)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:99)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:59)
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:55)
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:60)
        at android.app.Activity.performCreate(Activity.java:6309)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:166) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5563) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 
     Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class android.view.ViewStub
        at android.view.LayoutInflater.createView(LayoutInflater.java:654)
        at com.qmuiteam.qmui.skin.QMUISkinLayoutInflaterFactory.onCreateView(QMUISkinLayoutInflaterFactory.java:63)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:880)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:843)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:521)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4162) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4234) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2054) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:99) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:59) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:55) 
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:60) 
        at android.app.Activity.performCreate(Activity.java:6309) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:166) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5563) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:628)
        at com.qmuiteam.qmui.skin.QMUISkinLayoutInflaterFactory.onCreateView(QMUISkinLayoutInflaterFactory.java:63) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:880) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:843) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:521) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4162) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4234) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2054) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:99) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:59) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:55) 
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:60) 
        at android.app.Activity.performCreate(Activity.java:6309) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:166) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5563) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.view.ViewConfiguration.get(ViewConfiguration.java:364)
        at android.view.View.<init>(View.java:3802)
        at android.view.ViewStub.<init>(ViewStub.java:107)
        at android.view.ViewStub.<init>(ViewStub.java:103)
        at android.view.ViewStub.<init>(ViewStub.java:99)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:628) 
        at com.qmuiteam.qmui.skin.QMUISkinLayoutInflaterFactory.onCreateView(QMUISkinLayoutInflaterFactory.java:63) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:880) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:843) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:521) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:4162) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4234) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2054) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:99) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:59) 
        at com.qmuiteam.qmui.util.QMUIStatusBarHelper.translucent(QMUIStatusBarHelper.java:55) 
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onCreate(QMUIFragmentActivity.java:60) 
        at android.app.Activity.performCreate(Activity.java:6309) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:166) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5563) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by lydlovezjr** [comment]
android 6.0.1 vivo手机

**Comment by cgspine** [comment]
2.0.0-alpha02 版本修复了
