### ISSUE TITLE
demo 有 BUG

### ISSUE THREAD

**Issue by jrfeng** [Tencent/QMUI_Android#787]
**复现步骤：**

* 清空 demo 的数据：存储空间 -> 清除数据
* 点击主界面弹出菜单的 **`Export SkinMaker Result`** 项，如下图所示

![201912160424012](https://user-images.githubusercontent.com/17897996/70907654-5b4f2580-2044-11ea-8d89-c8db95facb46.png)

#### 异常日志（堆栈） ####

```txt
2019-12-16 20:32:01.401 24070-24102/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.qmuiteam.qmuidemo, PID: 24070
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:325)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at com.qmuiteam.qmui.skin.QMUISkinMaker$ExportTask.doInBackground(QMUISkinMaker.java:846)
        at com.qmuiteam.qmui.skin.QMUISkinMaker$ExportTask.doInBackground(QMUISkinMaker.java:816)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:760) 
```

**Comment by jrfeng** [comment]
应该是没有对 `MMKV#allKeys():String[]` 方法返回 `null` 进行处理导致的。

查看 `MMKV` 的源码发现它的 [`allKeys()`](https://github.com/Tencent/MMKV/blob/a1ab8f8e7fc61b814b3b4c5c7365cb71942e6934/Android/MMKV/mmkv/src/main/cpp/native-bridge.cpp#L519) 方法是一个 `Nullable` 方法：

![360截图16210605236870](https://user-images.githubusercontent.com/17897996/70909132-c3ebd180-2047-11ea-99b6-6a0850e5f534.png)

**Comment by cgspine** [comment]
收到，谢谢反馈
