### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by luwei1991** [Tencent/QMUI_Android#812]
### 运行环境 ###

- [x] 设备型号： 华为m5青春版
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`2.0.2`

#### 异常日志（堆栈） ####
2020-01-03 10:17:14.499 21983-21983/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.product.sampling, PID: 21983
    java.lang.ClassCastException: com.bumptech.glide.manager.SupportRequestManagerFragment cannot be cast to com.qmuiteam.qmui.arch.QMUIFragment
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.getCurrentFragment(QMUIFragmentActivity.java:173)
        at com.qmuiteam.qmui.arch.QMUIFragmentActivity.onKeyDown(QMUIFragmentActivity.java:153)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2748)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3559)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:115)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:133)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:558)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2814)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:427)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5663)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5531)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5157)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5214)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5190)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5354)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2783)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2291)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2282)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2758)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:386)
        at android.os.Looper.loop(Looper.java:175)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by cgspine** [comment]
因为你的 SupportRequestManagerFragment 不是 QMUIFragment， 我改下这里的实现吧，不要求 getCurrentFragment 返回 QMUIFragment 好咯。

**Comment by cgspine** [comment]
可以升级到 2.0.0-alpha03，我去掉了强制类型约束
