### ISSUE TITLE
startFragmentAndDestroyCurrent 开启混淆后产生NullPointer异常

### ISSUE THREAD

**Issue by zhaobinliz** [Tencent/QMUI_Android#878]
### 运行环境 ###

- [x] 设备系统版本：Android 4.4, Android9.0
- [x] Gradle 版本：3.4.2
- [x] QMUI Android 版本：1.4.4

### 具体问题描述 ###
开启混淆后
        debug {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

proguard-rules.pro加入：
-keep class **_FragmentFinder { *; }
-keep class com.qmuiteam.qmui.arch.record.** { *; }
-keep class androidx.fragment.app.* { *; }

#### 异常日志（堆栈） ####
Android 4.4环境下：
04-07 10:15:39.761 6290-6290/com.qmuiteam.qmuidemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qmuiteam.qmuidemo, PID: 6290
    java.lang.NullPointerException
        at com.qmuiteam.qmui.arch.D.a(:167)
        at com.qmuiteam.qmui.arch.n.a(:190)
        at com.qmuiteam.qmui.arch.l.c(:220)
        at com.qmuiteam.qmui.arch.l.f(:198)
        at com.qmuiteam.qmuidemo.fragment.lab.QDArchTestFragment.a(:51)
        at com.qmuiteam.qmuidemo.fragment.lab.i.onClick(:87)
        at android.view.View.performClick(View.java:4438)
        at android.view.View$PerformClick.run(View.java:18422)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

Android 9.0环境下：
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qmuiteam.qmuidemo, PID: 18217
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.reflect.Field.setAccessible(boolean)' on a null object reference
        at com.qmuiteam.qmui.arch.D.a(:167)
        at com.qmuiteam.qmui.arch.n.a(:190)
        at com.qmuiteam.qmui.arch.l.c(:220)
        at com.qmuiteam.qmui.arch.l.f(:198)
        at com.qmuiteam.qmuidemo.fragment.lab.QDArchTestFragment.a(:51)
        at com.qmuiteam.qmuidemo.fragment.lab.i.onClick(:87)
        at android.view.View.performClick(View.java:6614)
        at android.view.View.performClickInternal(View.java:6587)
        at android.view.View.access$3100(View.java:787)
        at android.view.View$PerformClick.run(View.java:26122)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6831)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)

在不开启代码混淆的情况下，可以正常运行。请问可以怎么样设置proguard-rules.pro来规避这个问题吗？另外，测试过2.x版本下，开启混淆后，可以正常运行。

**Comment by cgspine** [comment]
-keep class androidx.fragment.app. { *; }

1.x 依赖的是support包版本的 fragment，没有开启 android.useAndroidX=true 和 android.enableJetifier=true ？
