### ISSUE TITLE
setFitsSystemWindows(boolean)NullPointerException空指针  

### ISSUE THREAD

**Issue by XD-Z** [Tencent/QMUI_Android#895]
### 运行环境 ###

- [x] 设备型号：如：`一加6T`
- [x] 设备系统版本：如 `Android 10.0`
- [x] Gradle 版本：如 `3.6.1`
- [x] QMUI Android 版本：`2.0.0-alpha04`

### 具体问题描述 ###
空指针异常，导致崩溃

#### 问题截图 ####

![1587363257(1)](https://user-images.githubusercontent.com/21350281/79719774-d9347d80-8311-11ea-9446-1f5c020fc154.jpg)

![1587363257(1)](https://user-images.githubusercontent.com/21350281/79719855-02550e00-8312-11ea-9c92-92589eded1a2.jpg)

#### 异常日志（堆栈） ####

 Process: com.tongdun.ent.finance, PID: 20679
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setFitsSystemWindows(boolean)' on a null object reference
        at com.qmuiteam.qmui.arch.QMUIFragment.newSwipeBackLayout(QMUIFragment.java:374)
        at com.qmuiteam.qmui.arch.QMUIFragment.onCreateView(QMUIFragment.java:724)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2696)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:284)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1324)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1564)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1641)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1705)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2497)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2284)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2239)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:2110)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
        at com.qmuiteam.qmui.arch.QMUIFragmentPagerAdapter.finishUpdate(QMUIFragmentPagerAdapter.java:105)
        at com.qmuiteam.qmui.widget.QMUIViewPager$WrapperPagerAdapter.finishUpdate(QMUIViewPager.java:203)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at com.qmuiteam.qmui.widget.QMUIViewPager.onMeasure(QMUIViewPager.java:109)
        at android.view.View.measure(View.java:24710)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24710)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.qmuiteam.qmui.layout.QMUIFrameLayout.onMeasure(QMUIFrameLayout.java:59)
        at android.view.View.measure(View.java:24710)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.qmuiteam.qmui.layout.QMUIFrameLayout.onMeasure(QMUIFrameLayout.java:59)
        at android.view.View.measure(View.java:24710)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:24710)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24710)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24710)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24710)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:749)
2020-04-20 14:08:34.845 20679-20679/? E/AndroidRuntime:     at android.view.View.measure(View.java:24710)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3259)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2042)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2337)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1930)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7988)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1154)
        at android.view.Choreographer.doCallbacks(Choreographer.java:977)
        at android.view.Choreographer.doFrame(Choreographer.java:893)
        at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:1082)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by XD-Z** [comment]
自己搞错了~~

**Comment by FKK-kun** [comment]
同样的异常！！，请问您是什么原因
